version: '3.7'

services:
  web:
    build: ./Yatube
    command: gunicorn Yatube.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./Yatube/:/usr/src/app/
      - static_volume:/usr/src/app/static
    expose:
      - 8000
    env_file:
      - ./.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

